sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t docker -f Dockerfile.dev .

script:
  - docker run -e CI=true docker npm run test -- -- coverage

after_success:
  - echo "Test success1"
